# START:test
# in ci_cd.yaml

# END:test
name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

# START:test
jobs:
  ci:
    runs-on: ubuntu-latest
    name: Compile with mix test
    env:
      MIX_ENV: test
    steps:
# END:test
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache deps directory
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Get dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix compile --warnings-as-errors

# START:test
      - name: Run tests
        run: mix test --max-failures 1 --trace --warnings-as-errors
# END:test
