# START: web_replicas
# in compose.yaml

# END: web_replicas
version: "3.9"

services:
  db:
    image: postgres:15.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pgpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}
    secrets:
      - pgpassword

# START: web_replicas
  web:
    image: ${WEB_IMAGE:-ghcr.io/beamops/kanban:latest}
    deploy:
      replicas: ${WEB_REPLICAS:-1}
      # END: web_replicas
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      PHX_HOST: "localhost"
    ports:
      - 4000:4000
    command: >
      bash -c "bin/migrate && \ 
               bin/server"
    depends_on:
      - db
    secrets:
      - databaseurl
      - secretkeybase

volumes:
  db_data:

secrets:
  pgpassword:
    file: ./secrets/.postgrespassword
  secretkeybase:
    file: ./secrets/.secretkeybase
  databaseurl:
    file: ./secrets/.databaseurl
