---
name: "Chapter 3 Integration"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    paths:
      - "build_and_dockerize_a_phoenix_liveview_application/**"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  OTP_VERSION: 26.2.1
  ELIXIR_VERSION: 1.16.0
  CHP_CODE_PATH: build_and_dockerize_a_phoenix_liveview_application

jobs:
  docker-build-and-co:
    name: "Ch CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: TEST CH 3 COMMANDS
        working-directory: ${{ env.CHP_CODE_PATH }}
        run: ./build_commands.sh
