#START:conditional-get-deps
# in ci_cd.yaml

#END:conditional-get-deps
name: CI/CD Elixir

on:
  push:
  workflow_dispatch:

#START:conditional-get-deps
jobs:
  ci:
    runs-on: ubuntu-latest
    name: Compile
    env:
      MIX_ENV: test
    steps:
    #END:conditional-get-deps
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache deps directory
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

#START:conditional-get-deps
      - name: Get dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get
#END:conditional-get-deps

      - run: mix compile --warnings-as-errors
